steps:
# Pull existing deployed images (used as a cache for unchanged steps)
- id: 'Pull backend image'
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:latest']
  waitFor: ['-'] # Don't wait for previous build steps

# Build images
- id: 'Build backend image'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--file'
  - 'services/backend/Dockerfile'
  - '--tag'
  - 'backend:latest'
  - '--tag'
  - 'gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:latest'
  - 'services/backend/.'
  waitFor: ['Pull backend image']

# Run containers in the background
- id: 'Run containers'
  name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '--file', 'services/docker-compose.yaml', 'up', '--detach']
  env:
  - 'NODE_ENV=test'
  waitFor: ['Build backend image']

# The "Run containers" step stops when containers are running, but before the services start running.
# The docker-start script performs steps such as installing dev dependencies and running migrations before starting the backend service.
# We ping the backend /health endpoint until we get a successful response, which indicates that pre-run steps are complete.
- id: 'Wait for backend'
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'compose'
  - '--file'
  - 'services/docker-compose.yaml'
  - 'exec'
  - '-T'
  - 'backend'
  - './scripts/wait-for.sh'
  - 'http://backend:3000/health'
  - '--timeout'
  - '300'
  waitFor: ['Run containers']

- id: 'Backend tests'
  name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '--file', 'services/docker-compose.yaml', 'exec', '-T', 'backend', 'npm', 'run', 'test']
  waitFor: ['Wait for backend']

- id: 'Backend Linting'
  name: 'gcr.io/cloud-builders/docker'
  args: ['compose', '--file', 'services/docker-compose.yaml', 'exec', '-T', 'backend', 'npm', 'run', 'lint']
  waitFor: ['Wait for backend']

- id: 'Push backend image to registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA']
  waitFor: ['Build backend image']

- id: 'Promote backend image to latest'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && gcloud container images add-tag gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:$SHORT_SHA gcr.io/$PROJECT_ID/$_BACKEND_SERVICE_NAME:latest || echo "skipping..."

substitutions: # default values
  _BACKEND_SERVICE_NAME: ''

timeout: 1800s
