name: onCommit
run-name: onCommit for ${{ github.sha }}
on: [push]
jobs:
  scan:
    runs-on: ubuntu-latest
    container: node:20
    defaults:
      run:
        working-directory: ./services/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: ls -la
      - run: npm install
      - run: node ./scripts/download-db-artifact.js
      - run: ls -la
      - run: ls -la downloaded
      - run: 'echo -e "Run: $(date +%s)" >> downloaded/database.txt'
      - run: 'echo "hello world" > other_artifact.txt'
      - uses: actions/upload-artifact@v4
        with:
          name: blockedtodo-database-test
          path: services/backend/downloaded/database.txt
      - uses: actions/upload-artifact@v4
        with:
          name: other_artifact
          path: services/backend/other_artifact.txt
      - run: 'npm run db:migrate'
      - run: 'node ./scripts/scan-this-codebase.js'
      - uses: actions/upload-artifact@v4
        with:
          name: blockedtodo-database
          path: services/backend/downloaded/database.db
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACTIONS_RUNTIME_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Environment variables to remove
      GITHUB_WEBHOOKS_SECRET: 'TODO: delete'
      GITHUB_APP_ID: 'TODO: delete'
      GITHUB_APP_PRIVATE_KEY: 'TODO: delete'
      GITHUB_CLIENT_ID: 'TODO: delete'
      GITHUB_CLIENT_SECRET: 'TODO: delete'
